### ISSUE TITLE
Fixes in v0

### ISSUE THREAD

**Issue by jitendra-1217** [Raghav-Sao/literature#4]
### Now

- Write tests for following very carefully, covering as much edge cases as possible:
  - [ ] Show endpoint
- Implement:
  - [ ] In show flow, check if all points made, if so mark game completed(broadcast event and etc.)
  - [ ] Verify route entries, Ensure game is running state for move/show endpoints(eg.)
  - [ ] Fix any TODO s added in code
  - [ ] Update toArray() method of models, add new attributes
  - [ ] Update postman collection
  - [ ] In nextTurn assignment, if user had no cards left, skip him. Such message to be broadcasted too.
  - [ ] Make a very simple single page(minimal) interface and play the game. Test thoroughly.
  - [ ] A job will query redis hash every sec(interval K1) by status and lastMoveMadeTimestamp (diff K2) and update nextTurn to prevTurn and publish this message to everyone.
  - [ ] Return proper response from show method: give pair of user and cards (which user have which card)
  - [ ] Can use 1 point for each card instead of current point

---

### Old

- [x] Define message structure: channel names, event types.
- [x] Publish appropriate message at needed endponits
- [x] Start the game when all user joined successfully
- [x] Partner validation - Define storage or rules, ensure validation.
- [x] Let's lowercase cards. Eg. h1 and not H1.
- [x] Make apis cleaner: Use post/patch conventions instead of all just get. :( 
- [x] Separate concern: session usage: user id , game id and those being passed as route param.
- [x] __Discussion required__ Update next turn & game status properly. Use game status in apis at places.
- [x] __Unit tests__ construct
- [x] Write more tests - Cover all endpoints(Functional) + Services(Unit test)
- [x] __Refactoring__: Chat message event payload
- [x] __Security__ ~~Pusher authentication for subscribing to channel.~~ For now it's public channels bcoz all the data there is public. Also, not everyone will be above to join bcoz the gameId is long random string(also the channel name)
- [x] __Discussion required__ Check for game completion in every move. Decide on how a game will terminate. Response structures for win (on some move).
- [x] __Refactoring__: Remove `phpunit.xml.dist` file

**Comment by Raghav-Sao** [comment]
Start the  game when all user joined successfully

**Comment by jitendra-1217** [comment]
- [x] Upload postman collection somewhere, maybe in codebase itself
- [x] Don't let ask for a card, one already has
- [ ] Show endpoint:
      - include partner, increment points - 1/2 to each user in case both contributed, else 1 to the user
      - check if all points made and then finish the game
- [ ] Time waiting limit for every player, next turn?
      - A job will query redis hash every sec(interval K1) by status and lastMoveMadeTimestamp (diff K2) and update nextTurn to prevTurn and publish this message to everyone.
      - Check to be added in move api
- [x] ** ~~__To check__:~~ Single player reached a combination where he can't ask for any card, game stuck at one single player - PASS, or wait for time limit. ^^~~
- [ ] In /game/move, if nextTurn user doesn't have effective card(basically, he can not ask for any new cards as he has made the suit(s)) then show his card and make his partner as nextTurn users.


---------------------------
- [ ] check that user has at least one card for from user in move action (opposition user = move From user), else rise exception.... b/c he will active in game with out having any card after submitting his all cards????

**Comment by jitendra-1217** [comment]
- [ ] Make a very simple **single page(minimal) interface** and play the game. Test thoroughly.

**Comment by jitendra-1217** [comment]
- [x] Move all string literals out to some constant file(s)
- [x] Clean tests file, most of it looks bad(too big line/ not understandable), break it and lines under 80. Flow and code should be understandable.
- [x] In code:
      - No expressions with if/for etc, use temporary variables
      - Lines under 80 char
      - Clean & understandable flow
- [x] Try removing try catch from controllers and putting it at one http exception handler (symfony framework)
- [ ] Ensure game is running state for move/show endpoints
